### ISSUE TITLE
how to export subtree

### ISSUE THREAD

**Issue by emin63** [titaniumbones/ox-slack#3]
This is great! Thanks!

One question: how do I export a sub-tree? Since this isn't in the usual export dispatcher, I don't see how to do that and for slack, usually what I want is a subtree.

Thanks again.

**Comment by titaniumbones** [comment]
Hi @emin63,

how nice to see that someone else is thinking of using this! 

This exporter is pretty primitive, and I purposely didn't put it in the dispatcher since my dispatcher is very crowded, and I normally just highlight a region and use a specialized function to perform the export.

In any case, something like `(org-slack-export-as-slack nil t)` would work.  The hydra that I use for this kind of stuff is as follows: 

``` emacs-lisp
(defhydra hydra-o-c (:color blue)
      "
  Export Region or file to clipboard
  ==================================
  To paste into a browser, libreoffice, etc, 
  choose \"_h_\" to use the rich-text system clipboard.

  Region is currently %s(if (use-region-p) \"ACTIVE.\" \"NOT ACTIVE!!!\").

  "

      ("m" (mwp-org-export-to-clipboard 'md) "as gfm md" :column "text"  )
      ("s" (mwp-org-export-to-clipboard 'slack) "as slack" :column "text" )
      ("h" ora-org-to-html-to-clipboard "to html clipboard" :column "html")
      ("H" (mwp-org-export-to-clipboard 'html) "to text as html"   :column "html"))
      
      
  (defun mwp-org-export-to-clipboard (fmt)
    "Export region to FMT, and copy to the kill ring for pasting into other programs."
    (interactive)
    (let* ((org-export-with-toc nil)
           (org-export-with-smart-quotes nil))
      (kill-new (org-export-as fmt t nil t))
      )

```

This lets me quickly select a region or subtree for pasting into some other document. Does that help?

**Comment by emin63** [comment]
Thanks for the suggestion of using `(org-slack-export-as-slack nil t)`. That works for me. When I get time, I'll look into the hydra version.

Thanks again for this package.
